name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -o StrictHostKeyChecking=no -r app ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/

      - name: Deploy container
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOC'
            cd app
            docker stop \$(docker ps -q) 2>/dev/null || true
            docker rm \$(docker ps -aq) 2>/dev/null || true
            docker build -t myapp .
            docker run -d -p 80:80 myapp
          EOC
