name: Deploy Flask App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known hosts
      run: ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ubuntu@${{ secrets.EC2_HOST }} << EOF2
          cd app || mkdir app && exit
          git pull origin main || true
          sudo docker build -t myapp .
          sudo docker stop \$(sudo docker ps -q) || true
          sudo docker run -d -p 80:80 myapp
        EOF2
